server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: test
    password: ^Xmu2q=%
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:/db/migration/common